platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'AppAuth'
end

target 'PluginTests' do
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
